name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: true
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name : Checkout
        uses: actions/checkout@v5
        with:
          show-progress: false

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: './global.json'

      - name: Print dotnet information
        run: dotnet --info

      - name: Build solution
        run: dotnet build -c Release

      - name: Run test
        working-directory: './test/LifeTimes.Tests'
        run: dotnet test -c Release --no-build