name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: true
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

jobs:
  run-tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name : Checkout
        uses: actions/checkout@v5
        with:
          show-progress: false

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: .NET information
        run: dotnet --info

      - name: Run test
        run: dotnet test './test/LifeTimes.Tests/LifeTimes.Tests.csproj' --logger 'trx;LogFileName=unit-tests.trx' -c Release --results-directory './artifacts'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: './artifacts'